output_strategy: "firebase"
csv_file_path: "nypd_data.csv"

redis:
  host: "localhost"
  port: 6379

kafka:
  bootstrap_servers: "localhost:9092"
  topic: "nypd_shootings"

firebase:
  key_path: "serviceAccountKey.json"